replicaCount: 2

image:
  repository: 192.168.122.1:5000/crypto
  tag: prod
  pullPolicy: Always

service:
  port: 8000

ingress:
  host: crypto.local

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
