{{- if .Values.postgres.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptoledger.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptoledger.labels" . | nindent 4 }}
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: crypto_ledger

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: {{ .Values.persistence.postgres.storageClass }}
        accessModes:
          - {{ .Values.persistence.postgres.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.postgres.size }}

{{- end }}
