apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptoledger
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/techie-guy92/cryptoledger_k8s.git
    targetRevision: develop
    path: helm
    helm:
      releaseName: crypto

  destination:
    server: https://kubernetes.default.svc
    namespace: crypto

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  revisionHistoryLimit: 5
