apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptoledger.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptoledger.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
