apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cryptoledger.fullname" . }}-migrate
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: {{ include "cryptoledger.fullname" . }}-config
        {{- if .Values.secrets.external }}
        - secretRef:
            name: {{ .Values.secrets.name }}
        {{- else }}
        - secretRef:
            name: {{ include "cryptoledger.fullname" . }}-secrets
        {{- end }}
        