apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres

  policyTypes:
    - Ingress

  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ include "cryptoledger.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
      - protocol: TCP
        port: 5432
