apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-config
  namespace: crypto
data:
  PROJECT_NAME: "crypto"
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: "config.settings"
  ENGINE_NAME: "django.db.backends.postgresql"
  DB_NAME: "crypto_ledger"
  # DB_HOST: "postgres.crypto.svc.cluster.local"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,crypto.local"
  # ALLOWED_HOSTS: "localhost,127.0.0.1,crypto.local,192.168.122.43,192.168.122.44,192.168.122.45,192.168.122.1"
  # CSRF_TRUSTED_ORIGINS: "http://localhost:8003,http://127.0.0.1:8003,http://crypto.local:8003,http://192.168.122.43:8003,http://crypto.local,http://crypto.local:80"
  CSRF_TRUSTED_ORIGINS: "http://localhost:8003,http://127.0.0.1:8003,http://crypto.local"
  FRONTEND_DOMAIN: "http://crypto.local"
  DEFAULT_PORT: "8003"
  SECURE_SSL_REDIRECT: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
  SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
  USE_X_FORWARDED_HOST: "True"
  USE_X_FORWARDED_PORT: "True"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  ACCESS_TOKEN: "15"
  REFRESH_TOKEN: "30"
  ROTATE_REFRESH_TOKENS: "False"
  BLACKLIST_AFTER_ROTATION: "True"
  