apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptoledger-config
  namespace: cryptoledger
data:
  PROJECT_NAME: "crypto"
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: "config.settings"
  ENGINE_NAME: "django.db.backends.postgresql"
  DB_NAME: "crypto_ledger"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: 587
  EMAIL_USE_TLS: True
  