apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-web
  namespace: crypto

spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: crypto
      tier: web
  template:
    metadata:
      labels:
        app: crypto
        tier: web

    spec:
      affinity:
        podAntiAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - crypto
                - key: tier
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname

      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}

        startupProbe:
          httpGet:
            path: /health/live/
            port: {{ .Values.service.port }}
            httpHeaders:
            - name: Host
              value: crypto.local
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 2

        readinessProbe:
          httpGet:
            path: /health/ready/
            port: {{ .Values.service.port }}
            httpHeaders:
            - name: Host
              value: crypto.local
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health/live/
            port: {{ .Values.service.port }}
            httpHeaders:
            - name: Host
              value: crypto.local
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        envFrom:
        - configMapRef:
            name: crypto-config
        - secretRef:
            name: crypto-secrets
        volumeMounts:
        - name: media
          mountPath: /app/media
          
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: crypto-media-pvc
