apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-web
  namespace: crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto
      tier: web
  template:
    metadata:
      labels:
        app: crypto
        tier: web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          # preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - crypto
                - key: tier
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: 192.168.122.1:5000/crypto:prod
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: crypto-config
        - secretRef:
            name: crypto-secrets
        volumeMounts:
        - name: media
          mountPath: /app/media
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: crypto-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-web
  namespace: crypto
spec:
  selector:
    app: crypto
    tier: web
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
