apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptoledger-web
  namespace: cryptoledger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptoledger
      tier: web
  template:
    metadata:
      labels:
        app: cryptoledger
        tier: web
    spec:
      containers:
      - name: web
        image: 192.168.122.1:5000/cryptoledger:prod
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: cryptoledger-config
        - secretRef:
            name: cryptoledger-secrets
        volumeMounts:
        - name: media
          mountPath: /app/media
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: cryptoledger-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cryptoledger-web
  namespace: cryptoledger
spec:
  selector:
    app: cryptoledger
    tier: web
  ports:
  - port: 8003
    targetPort: 8003
  type: NodePort
  