apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cryptoledger-ingress
  namespace: cryptoledger
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: crypto.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cryptoledger-web
            port:
              number: 8003
              