apiVersion: batch/v1
kind: Job
metadata:
  name: crypto-migrate
  namespace: crypto
spec:
  backoffLimit: 3
  template:
    spec:
      # hostNetwork: true
      restartPolicy: Never
      containers:
      - name: migrate
        image: 192.168.122.1:5000/cryptoledger:prod
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: crypto-config
        - secretRef:
            name: crypto-secrets
