apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-media-pvc
  namespace: crypto
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      