apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-media-pvc
  namespace: crypto
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
